### PR TITLE
Plaques

### PR DESCRIPTION
**Pull request by Dont-Copy-That-Floppy**
I don't know if these are something you want to include, but I used them when solving the puzzle for myself.

### CODE REVIEW

**Comment by r-pufky** [comment]
Great work, thanks!

Can you include an update to the main README.md file and include a link for each image on the achievement text? This will make it easier for future folks to see the images.

Example edit:
README.md
``` markdown
1. We’re Gonna Need a Bigger Boat [plaque](Plaques/As%20The%20four%20thieves%20stole%20the%20valuable%20weapon%20they%20also%20took%20all%20the%20munitions%20they%20could%20find.jpg)
```
%20 for spaces so links work properly, alternatively just rename using underscores (As_The_four_thieves_stole...); whatever option works best for you!

**Comment by Dont-Copy-That-Floppy** [comment]
No prob. Be happy to.

**Comment by Dont-Copy-That-Floppy** [comment]
Alright done. I've done you one better. Now, the title of the plaque is the link itself, and I've added the requirements for the achievements in a second column.

**Comment by Dont-Copy-That-Floppy** [comment]
If you want, I could put all your image files into a subdirectory, and relink the readme images to help clean up the directory.

**Comment by r-pufky** [comment]
Thanks for the changes! -- No worries on the cleanup, I was planning on running over again anyways after your images are in. A few things:

1. Put the S in laughterhouse changed to making a statement. See: https://github.com/r-pufky/payday2-secret/issues/16 -- likely the achievement text was not updated. Currently Put the S in laugherhouse has been confirmed to work over making a statement.
2. looting in the dark changed to the pacifist : See: https://github.com/r-pufky/payday2-secret/issues/3 -- if you have data to confirm pacifist over looting in the dark, update it in this bug; currently looting in the dark was confirmed in the original discussion.

**Comment by Dont-Copy-That-Floppy** [comment]
You're likely correct. These were the notes I had for the achievements, but I made those notes a little over a year ago. I'll check later today and update them if they changed.

**Comment by r-pufky** [comment]
Closing pull request, it's been over a year since it was cut. Please re-open and address issues / ask questions if you'd like to proceed.

Thanks for your efforts!

**Comment by Dont-Copy-That-Floppy** [comment]
Is your repo up to date with everything?

**Comment by r-pufky** [comment]
Yup head/main is current.

**Pull request closed without merging**
